### ISSUE TITLE
Avoid triggering the "onChange" event after setting a new value to the slider.

### ISSUE THREAD

**Issue by prototype23** [tyleryasaka/semantic-ui-range#12]
Hi it would be usefull to add an extra parameter on the method 'set value' in order to avoid triggering the onChange event.

I have an image editor and use your slider ui for the zoom.

User can use your slider to zoom the  image in/out. 
```
zoomSlider.range({
    min: 0.01,
    max: 2,
    step: 0.01,
    start: 1,
    onChange: function(val) {
        img.cropper('zoomTo',  val); 
   }
});
```
All ok wth the above code. But when image is zoomed by other input eg a mouse wheel, and we try to update the  semantic ui slider too, we fall into an  endless loop.
```
..
onZoom: function (e) {
    // Triggers when image has been zoomed. eg from mouseWheel event
    zoomSlider.range('set value', e.ratio);
}
..
```

**Comment by prototype23** [comment]
Something i found is to check the e.originalEvent. It seems, in my case, exists only when user interacted. 
```
onZoom: function (e) {
	if (e && e.originalEvent) {
		//if zoom came from user interaction only
		zoomSlider.range('set value', e.ratio);
	}
}
```

**Comment by tyleryasaka** [comment]
I've merged a change that should provide a solution to this problem. A second property is now passed to the `onChange` method. It's a hash with a `triggeredByUser` boolean parameter. This allows you to check whether the change was triggered by a user interacting with the slider or whether it was triggered programatically.

So you could do something like this:

    onChange: function(val, meta) {
        if(meta.triggeredByUser) {
            img.cropper('zoomTo',  val); 
        }
    }

And this should not cause an infinite loop.

**Comment by prototype23** [comment]
Thank you, your changes worked :)

I had customized your plugin with a similar way, passing an extra parameter to "set value" method but your's is better because the "onChange" callback is always triggered. Good  for those who rely on that callback in their code for some other reason.

👍

**Comment by tyleryasaka** [comment]
Awesome! 😃
