### ISSUE TITLE
Slider is not well initialized when element is in hidden parent

### ISSUE THREAD

**Issue by PapsOu** [tyleryasaka/semantic-ui-range#26]
The slider does not starts with the associated input when it is initialized in an hidden container.

see this codepen to reproduce the bug : https://codepen.io/anon/pen/vdqwxV

**Comment by kurt1288** [comment]
PR #27 didn't entirely fix this issue. In my case, I'm using submenus in Semantic and the slider is in a secondary submenu. In that case, it is still not initialized properly.

**Comment by PapsOu** [comment]
@kurt1288 If this problem still occurs, can you open a new issue ?
