### ISSUE TITLE
Merge into SUI fork

### ISSUE THREAD

**Issue by hammy2899** [tyleryasaka/semantic-ui-range#30]
I have recently created a community fork for semantic and we are wanting to merge your range module into it so it is a part of the core library.

Do you have anything against this and is there anything we should know before merging?

Fork: https://github.com/hammy2899/Fomantic-UI

**Comment by tyleryasaka** [comment]
@hammy2899 Please fork away! Would be honored for you to include it 😄

**Comment by hammy2899** [comment]
@tyleryasaka The range slider is now in the core [Fomantic](https://fomantic-ui.com/)
